In [66]:
import numpy as np

In [67]:
L=[1,2,3,4,5]

In [68]:
np.array(L)

array([1, 2, 3, 4, 5])

In [69]:
A=np.array(L)

In [70]:
A

array([1, 2, 3, 4, 5])

In [71]:
A.dtype

dtype('int32')

In [72]:
L=[1,2,3,[4,5,6],7,8,9]

In [73]:
A=np.array(L)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7,) + inhomogeneous part.

In [74]:
L=[[1,2,3],[4,5,6]]

In [75]:
A=np.array(L)

In [76]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
A.dtype

dtype('int32')

In [78]:
A.ndim

2

In [79]:
S={1,2,3,4}

In [80]:
A=np.array(S)

In [81]:
A

array({1, 2, 3, 4}, dtype=object)

In [82]:
A.dtype

dtype('O')

In [83]:
A.ndim

0

In [84]:
T=1,2,3,4

In [85]:
A=np.array(T)

In [86]:
A

array([1, 2, 3, 4])

In [87]:
A.ndim

1

In [88]:
L='Made in India'.split()

In [89]:
L

['Made', 'in', 'India']

In [90]:
A1=np.array(L)

In [91]:
A1

array(['Made', 'in', 'India'], dtype='<U5')

In [28]:
A2=np.array(L,dtype='i')

ValueError: invalid literal for int() with base 10: 'Made'

In [29]:
A12=np.array(A,dtype='f')

In [30]:
A12

array([1., 2., 3., 4.], dtype=float32)

In [31]:
A13=np.array(A,dtype='complex')

In [32]:
A13

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [33]:
A13.dtype

dtype('complex128')

In [34]:
A14=np.array(A,dtype='c16')

In [35]:
A14

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [37]:
A15=np.array(A,dtype='S')

In [38]:
A15

array([b'1', b'2', b'3', b'4'], dtype='|S11')

In [40]:
A15=np.array(A,dtype='U')

In [41]:
A15

array(['1', '2', '3', '4'], dtype='<U11')

In [42]:
A16=A.astype(A13.dtype)

In [43]:
A16

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [44]:
L2=[0,1,2,3,4]

In [45]:
A22=np.array(L2,dtype=bool)

In [46]:
A22

array([False,  True,  True,  True,  True])

In [47]:
A17=A.astype(A22.dtype)

In [48]:
A17

array([ True,  True,  True,  True])

In [49]:
A=np.arange(1,37)

In [50]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [51]:
A.size

36

In [52]:
A.reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [53]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [54]:
A33=A.reshape(2,3,6)

In [55]:
A33

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]],

       [[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]])

In [56]:
A33[0]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [58]:
B=A.reshape(2,2,3,3)

In [59]:
B

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]],


       [[[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]],

        [[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]]]])

In [60]:
B.ndim

4

In [61]:
B.dtype

dtype('int32')

In [62]:
C=np.arange((1,17),dtype='f')

TypeError: arange: scalar arguments expected instead of a tuple.

In [63]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [64]:
C=np.arange(1,17,dtype='f')

In [65]:
C

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.], dtype=float32)

In [92]:
A

array([1, 2, 3, 4])

In [94]:
A.reshape(2,2,inplace=True)

TypeError: 'inplace' is an invalid keyword argument for this function