In [1]:
import numpy as np

In [2]:
L1=[1,2,3,4,5,6]

In [3]:
A=np.array(L1)

In [4]:
A

array([1, 2, 3, 4, 5, 6])

In [5]:
print(type(A))

<class 'numpy.ndarray'>


In [6]:
A.size

6

In [7]:
A.shape

(6,)

In [8]:
A.ndim

1

In [9]:
B=A.reshape(2,3)

In [10]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
R1=B[0]

In [12]:
R1

array([1, 2, 3])

In [13]:
R1.shape

(3,)

In [14]:
B[:,0]

array([1, 4])

In [15]:
R1.ndim

1

In [16]:
R2=B[0:,]

In [17]:
R2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
R2.ndim

2

In [19]:
R2.shape

(2, 3)

In [20]:
R2[0:,0:1]

array([[1],
       [4]])

In [21]:
R3=B[0:1,]

In [22]:
R3

array([[1, 2, 3]])

In [23]:
R3.shape

(1, 3)

In [25]:
R3.ndim

2

In [26]:
R4=B[0:1,0:1]

In [27]:
R4

array([[1]])

In [28]:
R4.shape

(1, 1)

In [29]:
R5=B[0,0]

In [30]:
R5.shape

()

In [32]:
print(type(R5))

<class 'numpy.int32'>


In [33]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
B[0,0]=8

In [35]:
B

array([[8, 2, 3],
       [4, 5, 6]])

In [36]:
B[1]=[10,11,12]

In [37]:
B

array([[ 8,  2,  3],
       [10, 11, 12]])

In [41]:
B[0][0]

8