In [1]:
import numpy as np

In [2]:
A=np.arange(0,100,10)

In [3]:
A

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
A.size

10

In [5]:
A.reshape(5,-1)

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [6]:
A

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
b1=A%4==0

In [9]:
b1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [10]:
A[b1]

array([ 0, 20, 40, 60, 80])

In [11]:
A

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
A[b1]=0

In [14]:
A

array([ 0, 10,  0, 30,  0, 50,  0, 70,  0, 90])

In [22]:
b2=np.logical_and(A%5==0,A%6==0)

In [23]:
b2

array([False, False,  True,  True,  True, False,  True, False,  True,
        True])

In [24]:
B2=A[b2]

In [25]:
B2

array([ 0, 30,  0,  0,  0, 90])

In [27]:
A[b2]=1

In [28]:
A

array([ 1, 10,  1,  1,  1, 50,  1, 70,  1,  1])

In [29]:
b3=np.logical_or(A%4==0,A%5==0)

In [30]:
b3

array([False,  True, False, False, False,  True, False,  True, False,
       False])

In [31]:
B3=A[b3]

In [32]:
B3

array([10, 50, 70])

In [33]:
C=np.arange(1,19).reshape(3,6)

In [34]:
C

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [35]:
C[[0]]

array([[1, 2, 3, 4, 5, 6]])

In [36]:
C

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [37]:
C[[0,0]]

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [38]:
C[[1,2]]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [39]:
C[[[0]]]

array([[[1, 2, 3, 4, 5, 6]]])

In [40]:
C1=C[[[0]]]

In [41]:
C1.ndim

3

In [42]:
C1.shape

(1, 1, 6)

In [79]:
C[[0],[0]]

array([1])

In [80]:
D=C[[0],[0]]

In [81]:
D

array([1])

In [82]:
D.ndim

1

In [83]:
D.shape

(1,)

In [84]:
E=np.arange(1,17).reshape(4,4)

In [86]:
E

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [87]:
E.ndim

2

In [88]:
E[:,[0]]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [89]:
E[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [91]:
r1=[0,1];c1=[2,3]

In [92]:
E[r1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
F=E[[r1]]

In [95]:
F.ndim

3

In [98]:
F.shape

(1, 2, 4)

In [99]:
F

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [100]:
E[[0]]=np.zeros((1,4),dtype='i')

In [101]:
E

array([[ 0,  0,  0,  0],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [102]:
E[r1,c1]

array([0, 8])

In [103]:
E[r1]

array([[0, 0, 0, 0],
       [5, 6, 7, 8]])

In [104]:
E[[r1],[c1]]

array([[0, 8]])